// Code generated by MockGen. DO NOT EDIT.
// Source: userDao.go

// Package userDao is a generated GoMock package.
package userDao

import (
	reflect "reflect"

	models "github.com/abdulmalikraji/e-commerce/db/models"
	gomock "github.com/golang/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockDataAccess is a mock of DataAccess interface.
type MockDataAccess struct {
	ctrl     *gomock.Controller
	recorder *MockDataAccessMockRecorder
}

// MockDataAccessMockRecorder is the mock recorder for MockDataAccess.
type MockDataAccessMockRecorder struct {
	mock *MockDataAccess
}

// NewMockDataAccess creates a new mock instance.
func NewMockDataAccess(ctrl *gomock.Controller) *MockDataAccess {
	mock := &MockDataAccess{ctrl: ctrl}
	mock.recorder = &MockDataAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataAccess) EXPECT() *MockDataAccessMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockDataAccess) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDataAccessMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDataAccess)(nil).Delete), id)
}

// FindAll mocks base method.
func (m *MockDataAccess) FindAll() ([]models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].([]models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockDataAccessMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockDataAccess)(nil).FindAll))
}

// FindByEmail mocks base method.
func (m *MockDataAccess) FindByEmail(email string) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmail", email)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmail indicates an expected call of FindByEmail.
func (mr *MockDataAccessMockRecorder) FindByEmail(email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmail", reflect.TypeOf((*MockDataAccess)(nil).FindByEmail), email)
}

// FindById mocks base method.
func (m *MockDataAccess) FindById(id string) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", id)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockDataAccessMockRecorder) FindById(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockDataAccess)(nil).FindById), id)
}

// FindUserAddresses mocks base method.
func (m *MockDataAccess) FindUserAddresses(id string) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserAddresses", id)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserAddresses indicates an expected call of FindUserAddresses.
func (mr *MockDataAccessMockRecorder) FindUserAddresses(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserAddresses", reflect.TypeOf((*MockDataAccess)(nil).FindUserAddresses), id)
}

// FindUserCart mocks base method.
func (m *MockDataAccess) FindUserCart(id string) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserCart", id)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserCart indicates an expected call of FindUserCart.
func (mr *MockDataAccessMockRecorder) FindUserCart(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserCart", reflect.TypeOf((*MockDataAccess)(nil).FindUserCart), id)
}

// FindUserNotifications mocks base method.
func (m *MockDataAccess) FindUserNotifications(id string) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserNotifications", id)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserNotifications indicates an expected call of FindUserNotifications.
func (mr *MockDataAccessMockRecorder) FindUserNotifications(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserNotifications", reflect.TypeOf((*MockDataAccess)(nil).FindUserNotifications), id)
}

// FindUserOrders mocks base method.
func (m *MockDataAccess) FindUserOrders(id string) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserOrders", id)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserOrders indicates an expected call of FindUserOrders.
func (mr *MockDataAccessMockRecorder) FindUserOrders(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserOrders", reflect.TypeOf((*MockDataAccess)(nil).FindUserOrders), id)
}

// FindUserReviews mocks base method.
func (m *MockDataAccess) FindUserReviews(id string) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserReviews", id)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserReviews indicates an expected call of FindUserReviews.
func (mr *MockDataAccessMockRecorder) FindUserReviews(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserReviews", reflect.TypeOf((*MockDataAccess)(nil).FindUserReviews), id)
}

// Insert mocks base method.
func (m *MockDataAccess) Insert(item models.User) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", item)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockDataAccessMockRecorder) Insert(item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockDataAccess)(nil).Insert), item)
}

// IsEmailExists mocks base method.
func (m *MockDataAccess) IsEmailExists(email string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEmailExists", email)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsEmailExists indicates an expected call of IsEmailExists.
func (mr *MockDataAccessMockRecorder) IsEmailExists(email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEmailExists", reflect.TypeOf((*MockDataAccess)(nil).IsEmailExists), email)
}

// IsPhoneNumberExists mocks base method.
func (m *MockDataAccess) IsPhoneNumberExists(phone string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsPhoneNumberExists", phone)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsPhoneNumberExists indicates an expected call of IsPhoneNumberExists.
func (mr *MockDataAccessMockRecorder) IsPhoneNumberExists(phone interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsPhoneNumberExists", reflect.TypeOf((*MockDataAccess)(nil).IsPhoneNumberExists), phone)
}

// SoftDelete mocks base method.
func (m *MockDataAccess) SoftDelete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockDataAccessMockRecorder) SoftDelete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockDataAccess)(nil).SoftDelete), id)
}

// Transaction mocks base method.
func (m *MockDataAccess) Transaction(fn func(*gorm.DB) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transaction", fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Transaction indicates an expected call of Transaction.
func (mr *MockDataAccessMockRecorder) Transaction(fn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transaction", reflect.TypeOf((*MockDataAccess)(nil).Transaction), fn)
}

// Update mocks base method.
func (m *MockDataAccess) Update(item models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", item)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDataAccessMockRecorder) Update(item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDataAccess)(nil).Update), item)
}
