// Code generated by MockGen. DO NOT EDIT.
// Source: storeDao.go

// Package storeDao is a generated GoMock package.
package storeDao

import (
	reflect "reflect"

	models "github.com/abdulmalikraji/e-commerce/db/models"
	gomock "github.com/golang/mock/gomock"
)

// MockDataAccess is a mock of DataAccess interface.
type MockDataAccess struct {
	ctrl     *gomock.Controller
	recorder *MockDataAccessMockRecorder
}

// MockDataAccessMockRecorder is the mock recorder for MockDataAccess.
type MockDataAccessMockRecorder struct {
	mock *MockDataAccess
}

// NewMockDataAccess creates a new mock instance.
func NewMockDataAccess(ctrl *gomock.Controller) *MockDataAccess {
	mock := &MockDataAccess{ctrl: ctrl}
	mock.recorder = &MockDataAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataAccess) EXPECT() *MockDataAccessMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockDataAccess) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDataAccessMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDataAccess)(nil).Delete), id)
}

// FindAll mocks base method.
func (m *MockDataAccess) FindAll() ([]models.Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].([]models.Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockDataAccessMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockDataAccess)(nil).FindAll))
}

// FindById mocks base method.
func (m *MockDataAccess) FindById(id string) (models.Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", id)
	ret0, _ := ret[0].(models.Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockDataAccessMockRecorder) FindById(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockDataAccess)(nil).FindById), id)
}

// FindByName mocks base method.
func (m *MockDataAccess) FindByName(name string) ([]models.Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", name)
	ret0, _ := ret[0].([]models.Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockDataAccessMockRecorder) FindByName(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockDataAccess)(nil).FindByName), name)
}

// FindByOwnerID mocks base method.
func (m *MockDataAccess) FindByOwnerID(ownerId string) ([]models.Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByOwnerID", ownerId)
	ret0, _ := ret[0].([]models.Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByOwnerID indicates an expected call of FindByOwnerID.
func (mr *MockDataAccessMockRecorder) FindByOwnerID(ownerId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByOwnerID", reflect.TypeOf((*MockDataAccess)(nil).FindByOwnerID), ownerId)
}

// FindStoreProducts mocks base method.
func (m *MockDataAccess) FindStoreProducts(storeId string) (models.Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindStoreProducts", storeId)
	ret0, _ := ret[0].(models.Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindStoreProducts indicates an expected call of FindStoreProducts.
func (mr *MockDataAccessMockRecorder) FindStoreProducts(storeId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindStoreProducts", reflect.TypeOf((*MockDataAccess)(nil).FindStoreProducts), storeId)
}

// Insert mocks base method.
func (m *MockDataAccess) Insert(item models.Store) (models.Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", item)
	ret0, _ := ret[0].(models.Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockDataAccessMockRecorder) Insert(item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockDataAccess)(nil).Insert), item)
}

// SoftDelete mocks base method.
func (m *MockDataAccess) SoftDelete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockDataAccessMockRecorder) SoftDelete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockDataAccess)(nil).SoftDelete), id)
}

// Update mocks base method.
func (m *MockDataAccess) Update(item models.Store) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", item)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDataAccessMockRecorder) Update(item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDataAccess)(nil).Update), item)
}
