// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/supabase-community/auth-go (interfaces: Client)

// Package authenticator is a generated GoMock package.
package authenticator

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	auth "github.com/supabase-community/auth-go"
	types "github.com/supabase-community/auth-go/types"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// AdminAudit mocks base method.
func (m *MockClient) AdminAudit(arg0 types.AdminAuditRequest) (*types.AdminAuditResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminAudit", arg0)
	ret0, _ := ret[0].(*types.AdminAuditResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminAudit indicates an expected call of AdminAudit.
func (mr *MockClientMockRecorder) AdminAudit(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminAudit", reflect.TypeOf((*MockClient)(nil).AdminAudit), arg0)
}

// AdminCreateSSOProvider mocks base method.
func (m *MockClient) AdminCreateSSOProvider(arg0 types.AdminCreateSSOProviderRequest) (*types.AdminCreateSSOProviderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminCreateSSOProvider", arg0)
	ret0, _ := ret[0].(*types.AdminCreateSSOProviderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminCreateSSOProvider indicates an expected call of AdminCreateSSOProvider.
func (mr *MockClientMockRecorder) AdminCreateSSOProvider(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminCreateSSOProvider", reflect.TypeOf((*MockClient)(nil).AdminCreateSSOProvider), arg0)
}

// AdminCreateUser mocks base method.
func (m *MockClient) AdminCreateUser(arg0 types.AdminCreateUserRequest) (*types.AdminCreateUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminCreateUser", arg0)
	ret0, _ := ret[0].(*types.AdminCreateUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminCreateUser indicates an expected call of AdminCreateUser.
func (mr *MockClientMockRecorder) AdminCreateUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminCreateUser", reflect.TypeOf((*MockClient)(nil).AdminCreateUser), arg0)
}

// AdminDeleteSSOProvider mocks base method.
func (m *MockClient) AdminDeleteSSOProvider(arg0 types.AdminDeleteSSOProviderRequest) (*types.AdminDeleteSSOProviderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminDeleteSSOProvider", arg0)
	ret0, _ := ret[0].(*types.AdminDeleteSSOProviderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminDeleteSSOProvider indicates an expected call of AdminDeleteSSOProvider.
func (mr *MockClientMockRecorder) AdminDeleteSSOProvider(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminDeleteSSOProvider", reflect.TypeOf((*MockClient)(nil).AdminDeleteSSOProvider), arg0)
}

// AdminDeleteUser mocks base method.
func (m *MockClient) AdminDeleteUser(arg0 types.AdminDeleteUserRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminDeleteUser", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AdminDeleteUser indicates an expected call of AdminDeleteUser.
func (mr *MockClientMockRecorder) AdminDeleteUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminDeleteUser", reflect.TypeOf((*MockClient)(nil).AdminDeleteUser), arg0)
}

// AdminDeleteUserFactor mocks base method.
func (m *MockClient) AdminDeleteUserFactor(arg0 types.AdminDeleteUserFactorRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminDeleteUserFactor", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AdminDeleteUserFactor indicates an expected call of AdminDeleteUserFactor.
func (mr *MockClientMockRecorder) AdminDeleteUserFactor(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminDeleteUserFactor", reflect.TypeOf((*MockClient)(nil).AdminDeleteUserFactor), arg0)
}

// AdminGenerateLink mocks base method.
func (m *MockClient) AdminGenerateLink(arg0 types.AdminGenerateLinkRequest) (*types.AdminGenerateLinkResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminGenerateLink", arg0)
	ret0, _ := ret[0].(*types.AdminGenerateLinkResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminGenerateLink indicates an expected call of AdminGenerateLink.
func (mr *MockClientMockRecorder) AdminGenerateLink(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminGenerateLink", reflect.TypeOf((*MockClient)(nil).AdminGenerateLink), arg0)
}

// AdminGetSSOProvider mocks base method.
func (m *MockClient) AdminGetSSOProvider(arg0 types.AdminGetSSOProviderRequest) (*types.AdminGetSSOProviderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminGetSSOProvider", arg0)
	ret0, _ := ret[0].(*types.AdminGetSSOProviderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminGetSSOProvider indicates an expected call of AdminGetSSOProvider.
func (mr *MockClientMockRecorder) AdminGetSSOProvider(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminGetSSOProvider", reflect.TypeOf((*MockClient)(nil).AdminGetSSOProvider), arg0)
}

// AdminGetUser mocks base method.
func (m *MockClient) AdminGetUser(arg0 types.AdminGetUserRequest) (*types.AdminGetUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminGetUser", arg0)
	ret0, _ := ret[0].(*types.AdminGetUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminGetUser indicates an expected call of AdminGetUser.
func (mr *MockClientMockRecorder) AdminGetUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminGetUser", reflect.TypeOf((*MockClient)(nil).AdminGetUser), arg0)
}

// AdminListSSOProviders mocks base method.
func (m *MockClient) AdminListSSOProviders() (*types.AdminListSSOProvidersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminListSSOProviders")
	ret0, _ := ret[0].(*types.AdminListSSOProvidersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminListSSOProviders indicates an expected call of AdminListSSOProviders.
func (mr *MockClientMockRecorder) AdminListSSOProviders() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminListSSOProviders", reflect.TypeOf((*MockClient)(nil).AdminListSSOProviders))
}

// AdminListUserFactors mocks base method.
func (m *MockClient) AdminListUserFactors(arg0 types.AdminListUserFactorsRequest) (*types.AdminListUserFactorsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminListUserFactors", arg0)
	ret0, _ := ret[0].(*types.AdminListUserFactorsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminListUserFactors indicates an expected call of AdminListUserFactors.
func (mr *MockClientMockRecorder) AdminListUserFactors(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminListUserFactors", reflect.TypeOf((*MockClient)(nil).AdminListUserFactors), arg0)
}

// AdminListUsers mocks base method.
func (m *MockClient) AdminListUsers(arg0 types.AdminListUsersRequest) (*types.AdminListUsersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminListUsers", arg0)
	ret0, _ := ret[0].(*types.AdminListUsersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminListUsers indicates an expected call of AdminListUsers.
func (mr *MockClientMockRecorder) AdminListUsers(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminListUsers", reflect.TypeOf((*MockClient)(nil).AdminListUsers), arg0)
}

// AdminUpdateSSOProvider mocks base method.
func (m *MockClient) AdminUpdateSSOProvider(arg0 types.AdminUpdateSSOProviderRequest) (*types.AdminUpdateSSOProviderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminUpdateSSOProvider", arg0)
	ret0, _ := ret[0].(*types.AdminUpdateSSOProviderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminUpdateSSOProvider indicates an expected call of AdminUpdateSSOProvider.
func (mr *MockClientMockRecorder) AdminUpdateSSOProvider(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminUpdateSSOProvider", reflect.TypeOf((*MockClient)(nil).AdminUpdateSSOProvider), arg0)
}

// AdminUpdateUser mocks base method.
func (m *MockClient) AdminUpdateUser(arg0 types.AdminUpdateUserRequest) (*types.AdminUpdateUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminUpdateUser", arg0)
	ret0, _ := ret[0].(*types.AdminUpdateUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminUpdateUser indicates an expected call of AdminUpdateUser.
func (mr *MockClientMockRecorder) AdminUpdateUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminUpdateUser", reflect.TypeOf((*MockClient)(nil).AdminUpdateUser), arg0)
}

// AdminUpdateUserFactor mocks base method.
func (m *MockClient) AdminUpdateUserFactor(arg0 types.AdminUpdateUserFactorRequest) (*types.AdminUpdateUserFactorResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminUpdateUserFactor", arg0)
	ret0, _ := ret[0].(*types.AdminUpdateUserFactorResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminUpdateUserFactor indicates an expected call of AdminUpdateUserFactor.
func (mr *MockClientMockRecorder) AdminUpdateUserFactor(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminUpdateUserFactor", reflect.TypeOf((*MockClient)(nil).AdminUpdateUserFactor), arg0)
}

// Authorize mocks base method.
func (m *MockClient) Authorize(arg0 types.AuthorizeRequest) (*types.AuthorizeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authorize", arg0)
	ret0, _ := ret[0].(*types.AuthorizeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authorize indicates an expected call of Authorize.
func (mr *MockClientMockRecorder) Authorize(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authorize", reflect.TypeOf((*MockClient)(nil).Authorize), arg0)
}

// ChallengeFactor mocks base method.
func (m *MockClient) ChallengeFactor(arg0 types.ChallengeFactorRequest) (*types.ChallengeFactorResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChallengeFactor", arg0)
	ret0, _ := ret[0].(*types.ChallengeFactorResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChallengeFactor indicates an expected call of ChallengeFactor.
func (mr *MockClientMockRecorder) ChallengeFactor(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChallengeFactor", reflect.TypeOf((*MockClient)(nil).ChallengeFactor), arg0)
}

// EnrollFactor mocks base method.
func (m *MockClient) EnrollFactor(arg0 types.EnrollFactorRequest) (*types.EnrollFactorResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnrollFactor", arg0)
	ret0, _ := ret[0].(*types.EnrollFactorResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnrollFactor indicates an expected call of EnrollFactor.
func (mr *MockClientMockRecorder) EnrollFactor(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnrollFactor", reflect.TypeOf((*MockClient)(nil).EnrollFactor), arg0)
}

// GetSettings mocks base method.
func (m *MockClient) GetSettings() (*types.SettingsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSettings")
	ret0, _ := ret[0].(*types.SettingsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSettings indicates an expected call of GetSettings.
func (mr *MockClientMockRecorder) GetSettings() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSettings", reflect.TypeOf((*MockClient)(nil).GetSettings))
}

// GetUser mocks base method.
func (m *MockClient) GetUser() (*types.UserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser")
	ret0, _ := ret[0].(*types.UserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockClientMockRecorder) GetUser() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockClient)(nil).GetUser))
}

// HealthCheck mocks base method.
func (m *MockClient) HealthCheck() (*types.HealthCheckResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HealthCheck")
	ret0, _ := ret[0].(*types.HealthCheckResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockClientMockRecorder) HealthCheck() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockClient)(nil).HealthCheck))
}

// Invite mocks base method.
func (m *MockClient) Invite(arg0 types.InviteRequest) (*types.InviteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Invite", arg0)
	ret0, _ := ret[0].(*types.InviteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Invite indicates an expected call of Invite.
func (mr *MockClientMockRecorder) Invite(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Invite", reflect.TypeOf((*MockClient)(nil).Invite), arg0)
}

// Logout mocks base method.
func (m *MockClient) Logout() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout")
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockClientMockRecorder) Logout() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockClient)(nil).Logout))
}

// Magiclink mocks base method.
func (m *MockClient) Magiclink(arg0 types.MagiclinkRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Magiclink", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Magiclink indicates an expected call of Magiclink.
func (mr *MockClientMockRecorder) Magiclink(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Magiclink", reflect.TypeOf((*MockClient)(nil).Magiclink), arg0)
}

// OTP mocks base method.
func (m *MockClient) OTP(arg0 types.OTPRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OTP", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// OTP indicates an expected call of OTP.
func (mr *MockClientMockRecorder) OTP(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OTP", reflect.TypeOf((*MockClient)(nil).OTP), arg0)
}

// Reauthenticate mocks base method.
func (m *MockClient) Reauthenticate() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reauthenticate")
	ret0, _ := ret[0].(error)
	return ret0
}

// Reauthenticate indicates an expected call of Reauthenticate.
func (mr *MockClientMockRecorder) Reauthenticate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reauthenticate", reflect.TypeOf((*MockClient)(nil).Reauthenticate))
}

// Recover mocks base method.
func (m *MockClient) Recover(arg0 types.RecoverRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recover", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Recover indicates an expected call of Recover.
func (mr *MockClientMockRecorder) Recover(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recover", reflect.TypeOf((*MockClient)(nil).Recover), arg0)
}

// RefreshToken mocks base method.
func (m *MockClient) RefreshToken(arg0 string) (*types.TokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", arg0)
	ret0, _ := ret[0].(*types.TokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockClientMockRecorder) RefreshToken(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockClient)(nil).RefreshToken), arg0)
}

// SAMLACS mocks base method.
func (m *MockClient) SAMLACS(arg0 *http.Request) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SAMLACS", arg0)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SAMLACS indicates an expected call of SAMLACS.
func (mr *MockClientMockRecorder) SAMLACS(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SAMLACS", reflect.TypeOf((*MockClient)(nil).SAMLACS), arg0)
}

// SAMLMetadata mocks base method.
func (m *MockClient) SAMLMetadata() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SAMLMetadata")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SAMLMetadata indicates an expected call of SAMLMetadata.
func (mr *MockClientMockRecorder) SAMLMetadata() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SAMLMetadata", reflect.TypeOf((*MockClient)(nil).SAMLMetadata))
}

// SSO mocks base method.
func (m *MockClient) SSO(arg0 types.SSORequest) (*types.SSOResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SSO", arg0)
	ret0, _ := ret[0].(*types.SSOResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SSO indicates an expected call of SSO.
func (mr *MockClientMockRecorder) SSO(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SSO", reflect.TypeOf((*MockClient)(nil).SSO), arg0)
}

// SignInWithEmailPassword mocks base method.
func (m *MockClient) SignInWithEmailPassword(arg0, arg1 string) (*types.TokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignInWithEmailPassword", arg0, arg1)
	ret0, _ := ret[0].(*types.TokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignInWithEmailPassword indicates an expected call of SignInWithEmailPassword.
func (mr *MockClientMockRecorder) SignInWithEmailPassword(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignInWithEmailPassword", reflect.TypeOf((*MockClient)(nil).SignInWithEmailPassword), arg0, arg1)
}

// SignInWithIdToken mocks base method.
func (m *MockClient) SignInWithIdToken(arg0, arg1, arg2, arg3, arg4 string) (*types.TokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignInWithIdToken", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(*types.TokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignInWithIdToken indicates an expected call of SignInWithIdToken.
func (mr *MockClientMockRecorder) SignInWithIdToken(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignInWithIdToken", reflect.TypeOf((*MockClient)(nil).SignInWithIdToken), arg0, arg1, arg2, arg3, arg4)
}

// SignInWithPhonePassword mocks base method.
func (m *MockClient) SignInWithPhonePassword(arg0, arg1 string) (*types.TokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignInWithPhonePassword", arg0, arg1)
	ret0, _ := ret[0].(*types.TokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignInWithPhonePassword indicates an expected call of SignInWithPhonePassword.
func (mr *MockClientMockRecorder) SignInWithPhonePassword(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignInWithPhonePassword", reflect.TypeOf((*MockClient)(nil).SignInWithPhonePassword), arg0, arg1)
}

// Signup mocks base method.
func (m *MockClient) Signup(arg0 types.SignupRequest) (*types.SignupResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Signup", arg0)
	ret0, _ := ret[0].(*types.SignupResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signup indicates an expected call of Signup.
func (mr *MockClientMockRecorder) Signup(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signup", reflect.TypeOf((*MockClient)(nil).Signup), arg0)
}

// Token mocks base method.
func (m *MockClient) Token(arg0 types.TokenRequest) (*types.TokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Token", arg0)
	ret0, _ := ret[0].(*types.TokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Token indicates an expected call of Token.
func (mr *MockClientMockRecorder) Token(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Token", reflect.TypeOf((*MockClient)(nil).Token), arg0)
}

// UnenrollFactor mocks base method.
func (m *MockClient) UnenrollFactor(arg0 types.UnenrollFactorRequest) (*types.UnenrollFactorResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnenrollFactor", arg0)
	ret0, _ := ret[0].(*types.UnenrollFactorResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnenrollFactor indicates an expected call of UnenrollFactor.
func (mr *MockClientMockRecorder) UnenrollFactor(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnenrollFactor", reflect.TypeOf((*MockClient)(nil).UnenrollFactor), arg0)
}

// UpdateUser mocks base method.
func (m *MockClient) UpdateUser(arg0 types.UpdateUserRequest) (*types.UpdateUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", arg0)
	ret0, _ := ret[0].(*types.UpdateUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockClientMockRecorder) UpdateUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockClient)(nil).UpdateUser), arg0)
}

// Verify mocks base method.
func (m *MockClient) Verify(arg0 types.VerifyRequest) (*types.VerifyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", arg0)
	ret0, _ := ret[0].(*types.VerifyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Verify indicates an expected call of Verify.
func (mr *MockClientMockRecorder) Verify(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockClient)(nil).Verify), arg0)
}

// VerifyFactor mocks base method.
func (m *MockClient) VerifyFactor(arg0 types.VerifyFactorRequest) (*types.VerifyFactorResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyFactor", arg0)
	ret0, _ := ret[0].(*types.VerifyFactorResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyFactor indicates an expected call of VerifyFactor.
func (mr *MockClientMockRecorder) VerifyFactor(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyFactor", reflect.TypeOf((*MockClient)(nil).VerifyFactor), arg0)
}

// VerifyForUser mocks base method.
func (m *MockClient) VerifyForUser(arg0 types.VerifyForUserRequest) (*types.VerifyForUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyForUser", arg0)
	ret0, _ := ret[0].(*types.VerifyForUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyForUser indicates an expected call of VerifyForUser.
func (mr *MockClientMockRecorder) VerifyForUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyForUser", reflect.TypeOf((*MockClient)(nil).VerifyForUser), arg0)
}

// WithClient mocks base method.
func (m *MockClient) WithClient(arg0 http.Client) auth.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithClient", arg0)
	ret0, _ := ret[0].(auth.Client)
	return ret0
}

// WithClient indicates an expected call of WithClient.
func (mr *MockClientMockRecorder) WithClient(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithClient", reflect.TypeOf((*MockClient)(nil).WithClient), arg0)
}

// WithCustomAuthURL mocks base method.
func (m *MockClient) WithCustomAuthURL(arg0 string) auth.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithCustomAuthURL", arg0)
	ret0, _ := ret[0].(auth.Client)
	return ret0
}

// WithCustomAuthURL indicates an expected call of WithCustomAuthURL.
func (mr *MockClientMockRecorder) WithCustomAuthURL(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithCustomAuthURL", reflect.TypeOf((*MockClient)(nil).WithCustomAuthURL), arg0)
}

// WithToken mocks base method.
func (m *MockClient) WithToken(arg0 string) auth.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithToken", arg0)
	ret0, _ := ret[0].(auth.Client)
	return ret0
}

// WithToken indicates an expected call of WithToken.
func (mr *MockClientMockRecorder) WithToken(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithToken", reflect.TypeOf((*MockClient)(nil).WithToken), arg0)
}
