// Code generated by MockGen. DO NOT EDIT.
// Source: userTokenDao.go

// Package userTokenDao is a generated GoMock package.
package userTokenDao

import (
	reflect "reflect"

	models "github.com/abdulmalikraji/e-commerce/db/models"
	gomock "github.com/golang/mock/gomock"
)

// MockDataAccess is a mock of DataAccess interface.
type MockDataAccess struct {
	ctrl     *gomock.Controller
	recorder *MockDataAccessMockRecorder
}

// MockDataAccessMockRecorder is the mock recorder for MockDataAccess.
type MockDataAccessMockRecorder struct {
	mock *MockDataAccess
}

// NewMockDataAccess creates a new mock instance.
func NewMockDataAccess(ctrl *gomock.Controller) *MockDataAccess {
	mock := &MockDataAccess{ctrl: ctrl}
	mock.recorder = &MockDataAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataAccess) EXPECT() *MockDataAccessMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockDataAccess) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDataAccessMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDataAccess)(nil).Delete), id)
}

// DeleteExpiredTokens mocks base method.
func (m *MockDataAccess) DeleteExpiredTokens() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpiredTokens")
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExpiredTokens indicates an expected call of DeleteExpiredTokens.
func (mr *MockDataAccessMockRecorder) DeleteExpiredTokens() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpiredTokens", reflect.TypeOf((*MockDataAccess)(nil).DeleteExpiredTokens))
}

// FindById mocks base method.
func (m *MockDataAccess) FindById(id string) (models.UserToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", id)
	ret0, _ := ret[0].(models.UserToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockDataAccessMockRecorder) FindById(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockDataAccess)(nil).FindById), id)
}

// FindByRefreshToken mocks base method.
func (m *MockDataAccess) FindByRefreshToken(refreshToken string) (models.UserToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByRefreshToken", refreshToken)
	ret0, _ := ret[0].(models.UserToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByRefreshToken indicates an expected call of FindByRefreshToken.
func (mr *MockDataAccessMockRecorder) FindByRefreshToken(refreshToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByRefreshToken", reflect.TypeOf((*MockDataAccess)(nil).FindByRefreshToken), refreshToken)
}

// FindByUserID mocks base method.
func (m *MockDataAccess) FindByUserID(userID string) ([]models.UserToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", userID)
	ret0, _ := ret[0].([]models.UserToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockDataAccessMockRecorder) FindByUserID(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockDataAccess)(nil).FindByUserID), userID)
}

// FindValidTokens mocks base method.
func (m *MockDataAccess) FindValidTokens(userID string) ([]models.UserToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindValidTokens", userID)
	ret0, _ := ret[0].([]models.UserToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindValidTokens indicates an expected call of FindValidTokens.
func (mr *MockDataAccessMockRecorder) FindValidTokens(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindValidTokens", reflect.TypeOf((*MockDataAccess)(nil).FindValidTokens), userID)
}

// Insert mocks base method.
func (m *MockDataAccess) Insert(item models.UserToken) (models.UserToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", item)
	ret0, _ := ret[0].(models.UserToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockDataAccessMockRecorder) Insert(item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockDataAccess)(nil).Insert), item)
}

// RevokeToken mocks base method.
func (m *MockDataAccess) RevokeToken(refreshToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeToken", refreshToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeToken indicates an expected call of RevokeToken.
func (mr *MockDataAccessMockRecorder) RevokeToken(refreshToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeToken", reflect.TypeOf((*MockDataAccess)(nil).RevokeToken), refreshToken)
}

// SoftDelete mocks base method.
func (m *MockDataAccess) SoftDelete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockDataAccessMockRecorder) SoftDelete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockDataAccess)(nil).SoftDelete), id)
}

// Update mocks base method.
func (m *MockDataAccess) Update(item models.UserToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", item)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDataAccessMockRecorder) Update(item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDataAccess)(nil).Update), item)
}
